# -*- coding: utf-8 -*-
"""Clustering

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pgfx7MU8TfWAtZJwtjqid7XfCU53JS_s
"""

import numpy as np
from sklearn.cluster import KMeans

data = np.array([[1,1],[3,4],[2,5],[1,4],[6,8],[5,4],[3,6],[7,4]])

model = KMeans(n_clusters=3)

clusters = model.fit(data)

clusters.cluster_centers_

clusters.predict([[1,2]])

