# -*- coding: utf-8 -*-
"""Decision tree - iris

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VvXacUoQ_fUyo7B1rwWJo8lO41O4m58q
"""

import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score , accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

data = load_iris()
x= data.data
y = data.target

x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.3)

model = DecisionTreeClassifier(criterion='entropy')

model.fit(x_train , y_train)

y_pred = model.predict(x_test)

r2_score(y_test , y_pred)

accuracy_score(y_test , y_pred)

