# -*- coding: utf-8 -*-
"""Factor Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1uE5QRGTEmPIjFCH5oLxcaIsJJDs4kq
"""

import numpy as np
import pandas as pd
from sklearn.decomposition import FactorAnalysis
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

data = pd.read_csv('data.csv')
data.head()

X = data.drop('1',axis=1,inplace=True)
X = data.rename(columns={'6':'n1','148':'n2','35':'n4','0':'n5','33.6':'n6','0.627':'n7','50':'n8','72':'n3'})
X

X.plot(kind='scatter', x='n2', y='n3', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

X.corr()

ss = StandardScaler()
X_scale = ss.fit_transform(X)
X_scale

factor_analysis = FactorAnalysis(n_components=4)

X_new = factor_analysis.fit_transform(X_scale)

X_new

factor_analysis.components_

factor_analysis.noise_variance_

X_new = pd.DataFrame(X_new,columns=('f1','f2','f3','f4'))
X_new

X_new.plot(kind='scatter', x='f2', y='f3', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)