# -*- coding: utf-8 -*-
"""LinearReg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xw371RM35cdCUAzuSnUHoS-1K-lKQNDv
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression as reg
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error as mse
from sklearn.metrics import r2_score as r2

data = pd.read_csv('weather.csv')

data.head()

x = data[['STA','YR','MO',"DA"]]
y = data[['MaxTemp']]

x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.3)

model = reg()

model.fit(x_train , y_train)

y_pred = model.predict(x_test)

mse(y_test , y_pred)

r2(y_test, y_pred)

