# -*- coding: utf-8 -*-
"""MLP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aEyeMVx9Er4qM1xDxlT37ZODxQZU-xHg
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

data = load_iris()
x  = data.data
y = data.target

x_train , x_test , y_train , y_test = train_test_split(x, y, test_size = 0.3)

model = MLPClassifier()

model.fit(x_train , y_train)

model.score(x_test , y_test)

