# -*- coding: utf-8 -*-
"""PCA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pgfx7MU8TfWAtZJwtjqid7XfCU53JS_s
"""

import numpy as np
from sklearn.decomposition import PCA

data = np.array([[1,1],[3,4],[2,5],[1,4],[6,8],[5,4],[3,6],[7,4]])

model = PCA(n_components=2)

model.fit_transform(data)

model.components_

