# -*- coding: utf-8 -*-
"""XboostReg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19V1Ah5wFfD-IFpSzCPvQO9wKGMCU-0U1
"""

import numpy as np
import xgboost
from  xgboost import XGBRegressor as xgr
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

data = pd.read_csv('kc_house_data.csv')

data.head(5)

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# data.describe()

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# data.hist(figsize=(20,12))

x = data.iloc[: , 3:]
y = data.iloc[: , 2]

xgboost.DMatrix(x,y)

x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.3)

model = xgr()

model.fit(x_train , y_train);

y_pred = model.predict(x_test)

r2_score(y_test,y_pred)

